name: Deploy to staging

on:
  push:
    branches:[main]

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH Into server
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@16.171.149.179 << 'EOF'
            cd week-25-ci-next-app/ && git pull
            pnpm install
            pnpm run build
            pm2 restart fe_server
            pm2 restart http_server
            pm2 restart ws_server
          EOF